language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
env:
  secure: Ueajuvsh6fjJxxEzntuwXrtd+RtxylRNVVsqxg/l56UAOTvZLExOFfa3sfSgPjBUncySsJDfnLvn9AbtX8nMV/EnZ1jNEKW+8GDFsnNL0wtzhsjjRB4g6d+TQTjOqB9H1qNnbQ5AUsqG1C32HxsegmziicHMg/zUmjKZJsPIYSHODVgd5VRCxrac4eAtYDpRiIKGVRDQ+PDdtXV0pNQ2iqO9m1Ck4Eiq94Q8bnqJB00oW5CLzxv76NfMQynFPlobPfS//bSw9fn3ZuTxEb5pGSzDJ0vpHEA6wWWa74X1vEKtfXAhHW9bjKup8/V/MF+Dtm78mKrVeRmKJkCklEIAXx1Djz6S/Lh77u8nV08uBiS2xX2IamdaecrUpar8Jtw38ejeeu3/4Ebjtv81j9cYSCiTeXI8LdtIJvglgiOrc/lvO7mRHaq7BtmS051vkdpdLOrFnbagB1HcGAyYloarEhqwSMxP1Z0IqtikdhDITYafCdAf4fm+BoBohJdpRZ9cDgWM7T5JX1VUJ2P6IZGsAK/wJyUSyn44kJQcCMo3vRooQAzKGxNV+aMZ+MVjy99FeuA7js82FjnY99WDNPh1vNG282LHGzOjIxv3wn9npjSTjXa3gO7uCA6CF1pA+VnAtOBCvJCEAau0FO9IfdTGF4Zk3n1af7j95Mgvmpf2FaM=
script: python setup.py test
